### nginx-proxy ###
version: '3'

services:
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./www:/var/www:ro
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl:ro
      - ./snippets:/etc/nginx/snippets
    networks:
      - proxy-tier

# Use an existing network
networks:
  proxy-tier:
    external:
      name: www-network
